language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
        - SYMFONY_PHPUNIT_VERSION="6.3"

matrix:
    fast_finish: true
    include:
          # Minimum supported dependencies with the latest and oldest PHP version
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"

          # Test the latest stable release
        - php: 7.1
        - php: 7.2
          env: COVERAGE=true BROWSCAP=true PHPUNIT_FLAGS="-v --coverage-text --coverage-clover coverage.xml"

          # Test LTS versions. This makes sure we do not use Symfony packages with version greater
          # than 2 or 3 respectively. Read more at https://github.com/symfony/lts
        - php: 7.2
          env: DEPENDENCIES="symfony/lts:^3"

          # Latest commit to master
        - php: 7.2
          env: STABILITY="dev"

    allow_failures:
          # Dev-master is allowed to fail.
        - env: STABILITY="dev"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
    - |
      if [[ $BROWSCAP == true ]]; then
        BROWSCAP_DIR=~/.phpenv/versions/$(phpenv version-name)
        wget http://browscap.org/stream?q=Lite_PHP_BrowsCapINI -O $BROWSCAP_DIR/browscap.ini
        echo "browscap='$BROWSCAP_DIR/browscap.ini'" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      fi

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - ./vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    # simple-phpunit is the PHPUnit wrapper provided by the PHPUnit Bridge component and
    # it helps with testing legacy code and deprecations (composer require symfony/phpunit-bridge)
    - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS

after_script:
    # upload coverage.xml file to Coveralls to analyze it
    # minimal required coverage is set to 80+ %
    - |
      if [[ $COVERAGE == "true" ]]; then
        wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        php coveralls.phar --verbose
      fi
